In [ ]:
/* Write your T-SQL query statement below */

SELECT 
    product_id,
    store1, store2, store3
FROM Products 
PIVOT(avg(price)
for store
in ([store1],[store2], [store3])) as pivottable